import { Comic } from './types';

export const comics: Comic[] = [
  {
    id: '1',
    title: 'Gundala',
    author: 'Hasmi',
    genre: 'Aksi',
    price: 45000,
    color: '#1a1a2e',
    description: 'Sancaka, seorang ilmuwan muda yang tersambar petir, bertransformasi menjadi Gundala Putera Petir untuk melindungi Indonesia dari kejahatan. Salah satu superhero ikonik Indonesia.',
    year: 1969,
    pages: 120,
  },
  {
    id: '2',
    title: 'Wiro Sableng 212',
    author: 'Bastian Tito',
    genre: 'Aksi',
    price: 35000,
    color: '#7f1d1d',
    description: 'Kisah pendekar silat bertato kapak maut 212 yang berkelana mencari ilmu dan membasmi kejahatan di tanah Jawa. Serial legendaris penuh aksi dan humor.',
    year: 1967,
    pages: 96,
  },
  {
    id: '3',
    title: 'Si Buta dari Goa Hantu',
    author: 'Ganes TH',
    genre: 'Petualangan',
    price: 30000,
    color: '#064e3b',
    description: 'Barda Mandrawata, seorang pendekar buta yang memiliki kemampuan luar biasa, berpetualang di seluruh nusantara sambil menegakkan keadilan.',
    year: 1967,
    pages: 110,
  },
  {
    id: '4',
    title: 'Panji Tengkorak',
    author: 'Hans Jaladara',
    genre: 'Horor',
    price: 40000,
    color: '#1c1917',
    description: 'Petualangan seorang pendekar misterius bertopeng tengkorak yang menelusuri dunia persilatan penuh intrik, racun, dan kematian.',
    year: 1968,
    pages: 130,
  },
  {
    id: '5',
    title: 'Sri Asih',
    author: 'R. A. Kosasih',
    genre: 'Aksi',
    price: 50000,
    color: '#4c1d95',
    description: 'Superheroine pertama Indonesia! Ani yang mendapat kekuatan dari dewi Sri melawan kejahatan dan melindungi masyarakat dengan kekuatan luar biasa.',
    year: 1954,
    pages: 104,
  },
  {
    id: '6',
    title: 'Garudayana',
    author: 'Is Yuniarto',
    genre: 'Fantasi',
    price: 55000,
    color: '#78350f',
    description: 'Pertualangan Kinara bersama Garuda muda bernama Garudayana dalam dunia yang terinspirasi dari mitologi dan epos Mahabharata versi modern.',
    year: 2009,
    pages: 152,
  },
  {
    id: '7',
    title: 'Si Juki',
    author: 'Faza Meonk',
    genre: 'Humor',
    price: 18000,
    color: '#0c4a6e',
    description: 'Kisah sehari-hari Juki, pemuda kocak yang selalu sial namun tak pernah putus semangat. Penuh jokes relatable kehidupan anak muda Indonesia.',
    year: 2012,
    pages: 80,
  },
  {
    id: '8',
    title: 'Godam',
    author: 'Wid NS',
    genre: 'Aksi',
    price: 42000,
    color: '#1e3a5f',
    description: 'Godam, manusia baja dari planet Covox yang terdampar di Bumi dan berjuang melindungi Indonesia sebagai superhero dengan kekuatan tak tertandingi.',
    year: 1969,
    pages: 118,
  },
  {
    id: '9',
    title: 'Benny & Mice',
    author: 'Benny Rachmadi & Muhammad Mice',
    genre: 'Humor',
    price: 22000,
    color: '#365314',
    description: 'Strip komik satire tentang kehidupan urban Jakarta dengan dua karakter ikonik yang mengomentari fenomena sosial, politik, dan budaya sehari-hari.',
    year: 2001,
    pages: 88,
  },
  {
    id: '10',
    title: 'Dendam Nyi Pelet',
    author: 'Jan Mintaraga',
    genre: 'Horor',
    price: 28000,
    color: '#3b0764',
    description: 'Kisah mistis tentang Nyi Pelet, sosok perempuan yang menggunakan ilmu hitam untuk membalas dendam. Diwarnai suasana horor khas Jawa yang mencekam.',
    year: 1970,
    pages: 100,
  },
  {
    id: '11',
    title: 'Cengkir Gading',
    author: 'Teguh Santosa',
    genre: 'Romantis',
    price: 32000,
    color: '#881337',
    description: 'Kisah cinta yang menyentuh hati antara dua jiwa yang terpisah oleh tradisi dan adat istiadat. Berlatar budaya Jawa yang kaya dan penuh makna.',
    year: 1972,
    pages: 92,
  },
  {
    id: '12',
    title: 'Nusantara 2044',
    author: 'Ario Anindito',
    genre: 'Petualangan',
    price: 60000,
    color: '#134e4a',
    description: 'Indonesia masa depan tahun 2044. Kelompok pahlawan muda berjuang mempertahankan nusantara dari ancaman teknologi asing yang ingin menguasai kepulauan.',
    year: 2020,
    pages: 168,
  },
];

export function formatRupiah(amount: number): string {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    maximumFractionDigits: 0,
  }).format(amount);
}

export const genres = ['Semua', 'Aksi', 'Petualangan', 'Humor', 'Horor', 'Romantis', 'Fantasi'];
